#!/bin/sh
./adb reboot bootloader
rm -f newboot.img-ramdisk.gz
echo 'zipping ./root to ./newboot.img-ramdisk.gz'
./zipramdisk root newboot.img-ramdisk.gz
./fastboot -c 'mem=471M console=ttyMSM2,115200n8 androidboot.hardware=thunderc' -b 12200000 boot boot.img-kernel newboot.img-ramdisk.gz
